/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_learn__2_1_Demo */

#ifndef _Included_kw_learn__2_1_Demo
#define _Included_kw_learn__2_1_Demo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_learn__2_1_Demo
 * Method:    getLine
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kw_learn__12_11_1Demo_getLine
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
