/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_test_example_CCout */

#ifndef _Included_kw_test_example_CCout
#define _Included_kw_test_example_CCout
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_test_example_CCout
 * Method:    cprint
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_kw_test_example_CCout_cprint
  (JNIEnv *, jobject);

/*
 * Class:     kw_test_example_CCout
 * Method:    cprint1
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_kw_test_example_CCout_cprint1
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
