/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_test_example_LuojiSo */

#ifndef _Included_kw_test_example_LuojiSo
#define _Included_kw_test_example_LuojiSo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_test_example_LuojiSo
 * Method:    ifTest
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_kw_test_example_LuojiSo_ifTest
  (JNIEnv *, jobject, jint);

/*
 * Class:     kw_test_example_LuojiSo
 * Method:    ifEslseTest
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kw_test_example_LuojiSo_ifEslseTest
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
