/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_test_example_CharTest */

#ifndef _Included_kw_test_example_CharTest
#define _Included_kw_test_example_CharTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_test_example_CharTest
 * Method:    charconvertNum
 * Signature: (C)I
 */
JNIEXPORT jint JNICALL Java_kw_test_example_CharTest_charconvertNum
  (JNIEnv *, jobject, jchar);

/*
 * Class:     kw_test_example_CharTest
 * Method:    getJniChar
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_kw_test_example_CharTest_getJniChar
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
