/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_test_example_MathUtils */

#ifndef _Included_kw_test_example_MathUtils
#define _Included_kw_test_example_MathUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_test_example_MathUtils
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_kw_test_example_MathUtils_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kw_test_example_MathUtils
 * Method:    minus
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_kw_test_example_MathUtils_minus
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     kw_test_example_MathUtils
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_kw_test_example_MathUtils_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
