/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class kw_test_example_StringTest */

#ifndef _Included_kw_test_example_StringTest
#define _Included_kw_test_example_StringTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     kw_test_example_StringTest
 * Method:    getStr
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kw_test_example_StringTest_getStr
  (JNIEnv *, jobject);

/*
 * Class:     kw_test_example_StringTest
 * Method:    sendStr
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_kw_test_example_StringTest_sendStr
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
