/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include<iostream>
/* Header for class org_example_Main */

#ifndef _Included_org_example_Main
#define _Included_org_example_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_example_Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_add
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_Main
 * Method:    min
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_min
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_Main
 * Method:    max
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_example_Main_max
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     org_example_Main
 * Method:    readArr
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_org_example_Main_readArr
  (JNIEnv *, jclass, jintArray);

#ifdef __cplusplus
}
#endif
#endif
